CHILD_UNITTESTS += /home/njohnson/sandbox/svunit-code/test/frmwrk_9/subdir1/subdir1a/subdir1a_unit_test.sv

INCDIR += /home/njohnson/sandbox/svunit-code/test/frmwrk_9/subdir1/subdir1a

CHILD_TESTSUITES = /home/njohnson/sandbox/svunit-code/test/frmwrk_9/subdir1/subdir1a/._home_njohnson_sandbox_svunit_code_test_frmwrk_9_subdir1_subdir1a_testsuite.sv



-include svunit.mk
include $(SVUNIT_INSTALL)/bin/cfg.mk
