#!/bin/bash

source test_functions.bsh

set_simulators

echo ----------------------------------
echo Running SVUNIT Regression Suite...
echo ----------------------------------
echo
echo Detected simulators: ${SVUNIT_SIMULATORS[@]}
echo

pass=1
function run_testlist {
  declare -a testlist=("${!1}")
  local sim=$2

  for test in ${testlist[@]}; do
    printf "Running %s... " $test
    cd $test && ./run > /dev/null 2>&1
    if [ "$?" != "0" ]; then
      printf "FAILED\n"
      pass=0
    else
      printf "PASSED\n"
    fi

    ./clean > /dev/null 2>&1

    cd - > /dev/null 2>&1
  done
}

# run the individual test groupings
declare -a frmwrk_tests
for test_dir in `ls -v -d frmwrk_*`; do
  if [ -f "$test_dir/run" ]; then
    frmwrk_tests+=($test_dir)
  fi
done
run_testlist frmwrk_tests[@]

declare -a sim_tests
for test_dir in `ls -v -d sim_*`; do
  if [ -f "$test_dir/run" ]; then
    frmwrk_tests+=($test_dir)
  fi
done
run_testlist sim_tests[@]

declare -a example_tests
example_tests=`ls -d example_*`
run_testlist example_tests[@]

declare -a mock_tests
mock_tests=`ls -d mock_*`
run_testlist mock_tests[@]

declare -a util_tests
util_tests=`ls -d util_*`
run_testlist util_tests[@]

declare -a wavedrom_tests
wavedrom_tests=`ls -d wavedrom_*`
run_testlist wavedrom_tests[@]


if [ "$pass" == "1" ]; then
  echo ----------------------------------
  echo SVUNIT Regression Suite PASSED
  echo ----------------------------------
else
  echo ----------------------------------
  echo SVUNIT Regression Suite FAILED
  echo ----------------------------------
fi
