UNITTESTS += /home/njohnson/work/svunit-code/examples/apb/apb_mst_unit_test.sv /home/njohnson/work/svunit-code/examples/apb/amba_xaction_unit_test.sv

TESTSUITES = /home/njohnson/work/svunit-code/examples/apb/._home_njohnson_work_svunit_code_examples_apb_testsuite.sv
._home_njohnson_work_svunit_code_examples_apb_UNITTESTS = /home/njohnson/work/svunit-code/examples/apb/apb_mst_unit_test.sv /home/njohnson/work/svunit-code/examples/apb/amba_xaction_unit_test.sv 

-include svunit.mk
include $(SVUNIT_INSTALL)/bin/cfg.mk
