INCDIR += /home/njohnson/work/svunit-code/examples/uvm/uvm_express /home/njohnson/work/svunit-code/examples/uvm/uvm_express /home/njohnson/work/svunit-code/examples/uvm/uvm_express /home/njohnson/work/svunit-code/examples/uvm/uvm_express

TESTSUITES = /home/njohnson/work/svunit-code/examples/uvm/uvm_express/._home_njohnson_work_svunit_code_examples_uvm_uvm_express_testsuite.sv
UNITTESTS = /home/njohnson/work/svunit-code/examples/uvm/uvm_express/apb_if_unit_test.sv /home/njohnson/work/svunit-code/examples/uvm/uvm_express/apb_mon_unit_test.sv /home/njohnson/work/svunit-code/examples/uvm/uvm_express/apb_coverage_unit_test.sv /home/njohnson/work/svunit-code/examples/uvm/uvm_express/apb_coverage_agent_unit_test.sv 

-include svunit.mk
include $(SVUNIT_INSTALL)/bin/cfg.mk
