UNITTESTS += /home/njohnson/work/svunit-code/test/svunit_base_0b/dut_unit_test.sv

TESTSUITES = /home/njohnson/work/svunit-code/test/svunit_base_0b/._home_njohnson_work_svunit_code_test_svunit_base_0b_testsuite.sv
._home_njohnson_work_svunit_code_test_svunit_base_0b_UNITTESTS = /home/njohnson/work/svunit-code/test/svunit_base_0b/dut_unit_test.sv 

-include svunit.mk
include $(SVUNIT_INSTALL)/bin/cfg.mk
