TESTSUITES = ._home_njohnson_work_svunit_code_examples_apb_testsuite.sv
._home_njohnson_work_svunit_code_examples_apb_UNITTESTS = apb_mst_unit_test.sv amba_xaction_unit_test.sv 

-include svunit.mk
include $(SVUNIT_INSTALL)/bin/cfg.mk
