#!/usr/bin/env bash

set -e

echo "Compiling production code"
qrun -compile queue.sv

echo "Compiling SVUnit"
qrun -compile \
    +incdir+../../../svunit_base/junit-xml \
    ../../../svunit_base/junit-xml/*.sv
qrun -compile \
    +incdir+../../../svunit_base \
    ../../../svunit_base/svunit_pkg.sv

echo "Compiling experimental extensions to SVUnit"
qrun -compile \
    +incdir+../../../svunit_base \
    +incdir+../../../src/experimental/sv \
    ../../../src/experimental/sv/svunit.sv

echo "Compiling test code"
qrun -compile \
    +incdir+../../../src/experimental/sv \
    +incdir+../../../svunit_base \
    queue_test.sv

echo "Running tests"
qrun ../../../src/experimental/sv/svunit_main.sv \
    -top svunit_main \
    -top queue_test \
    +SVUNIT_FILTER="*"
