#!/usr/bin/env bash

echo "Compiling production code"
xrun -compile factorial.sv

echo "Compiling SVUnit"
xrun -compile \
    -incdir ../../../svunit_base/junit-xml \
    ../../../svunit_base/junit-xml/*.sv
xrun -compile \
    -incdir ../../../svunit_base \
    ../../../svunit_base/svunit_pkg.sv

echo "Compiling test code"
xrun -compile factorial_test.sv

echo "Running tests"
xrun svunit_main.sv
